export const Genres = {
    A0_ALL :{id: 0, name: 'All Genres'},
    ADVENTURE: { id: 12, name: 'Adventure' },
    FANTASY: { id: 14, name: 'Fantasy' },
    ANIMATION: { id: 16, name: 'Animation' },
    DRAMA: { id: 18, name: 'Drama' },
    HORROR: { id: 27, name: 'Horror' },
    ACTION: { id: 28, name: 'Action' },
    COMEDY: { id: 35, name: 'Comedy' },
    WESTERN: { id: 37, name: 'Western' },
    HISTORY: { id: 36, name: 'History' },
    THRILLER: { id: 53, name: 'Thriller' },
    CRIME: { id: 80, name: 'Crime' },
    DOCUMENTARY: { id: 99, name: 'Documentary' },
    'SCIENCE FICTION': { id: 878, name: 'Science Fiction' },
    MYSTERY: { id: 9648, name: 'Mystery' },
    MUSIC: { id: 10402, name: 'Music' },
    ROMANCE: { id: 10749, name: 'Romance' },
    FAMILY: { id: 10751, name: 'Family' },
    WAR: { id: 10752, name: 'War' },
    'ACTION & ADVENTURE': { id: 10759, name: 'Action & Adventure' },
    KIDS: { id: 10762, name: 'Kids' },
    NEWS: { id: 10763, name: 'News' },
    REALITY: { id: 10764, name: 'Reality' },
    'SCI-FI & FANTASY': { id: 10765, name: 'Sci-Fi & Fantasy' },
    SOAP: { id: 10766, name: 'Soap' },
    TALK: { id: 10767, name: 'Talk' },
    'WAR & POLITICS': { id: 10768, name: 'War & Politics' },
    'TV MOVIE': { id: 10770, name: 'TV Movie' }
}
